apiVersion: apps/v1
kind: Deployment
metadata:
 name: typescript-node-server-ether-20525mds
 labels:
   app: typescript-node-server-ether-20525mds
spec:
 selector:
  matchLabels:
   app: typescript-node-server-ether-20525mds
 template:
  metadata:
   labels:
    app: typescript-node-server-ether-20525mds
  spec:
   containers:
   - image: ip_address_of_the_machine:5000/typescript-node-server-ether-20525mds:latest
     name: nodejs-api
     imagePullPolicy: Always
     ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: sample-nodejs-svc
spec:
    ports:
    - name: “sample-nodejs”
      targetPort: 3000
      port: 3000
      nodePort: 30253
      protocol: TCP
    selector:
       app: sample-nodejs
    type: NodePort