version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env  
    environment:
      POSTGRES_USER: postgres                
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      # POSTGRES_HOST_AUTH_METHOD=trust
      # PGDATA: /var/lib/postgresql/data/db

    expose:
       - "5432"
    ports:
       - "5432:5432"

  pgadmin:
      restart: always
      image: dpage/pgadmin4
      container_name: pgadmin1
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
        PGADMIN_DEFAULT_PASSWORD: postgres
        PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
        PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'


networks:
  web_network:
    driver: bridge  