version: "3"
services:
  postgres:
    image: postgres
    container_name: app_ether_todo_postgre
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env  
    environment:
      POSTGRES_USER: postgres                
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/db

    ports:
      - "5432:5432"

  pgadmin:
      restart: always
      image: dpage/pgadmin4
      container_name: app-ether-s20-todo-pgadmin
      depends_on:
        - postgres
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: joelotepawembo@gmail.com
        PGADMIN_DEFAULT_PASSWORD: abcde@12345   

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data        
volumes:
  progresDB:
  redisDB: