version: "3"
services:
  nodeserver:
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - "5000:5000"
  nodeserver2:
      build:
          context: ./myapp
          dockerfile: ./Dockerfile
      ports:
          - "3000:3000"       
  nginx:
      container_name: typescript-node-server-ether-20525mds
      restart: always
      build:
          context: ./nginx
          dockerfile: ./Dockerfile
      ports:
            - "80:80"